#!/bin/bash

function install_homebrew { 
  if ! [ -x "$(command -v brew)" ]; then
    echo "installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo "homebrew installed already"
  fi
}

function install_xcode_cli {
	xcode-select --install
}

function install_vim_with_lua {
	brew install vim --with-lua --override-system-vim
	echo $PATH=/usr/local/bin:$PATH
}

function install_vim_go_ide {
	brew install gotags
	#refactor
	git clone https://github.com/fatih/vim-go.git ~/.vim/bundle
	git clone https://github.com/Shougo/neocomplete.vim.git ~/.vim/bundle
	git clone https://github.com/farazdagi/vim-go-ide.git ~/.vim/bundle
	git clone https://github.com/majutsushi/tagbar.git ~/.vim/bundle

#execute vim command from commandline

}

function install_vim_plugin {
  if ![ -f "~/.vim/autoload/plug.vim" ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    echo "vim plugin installed already"
  fi
}

function install_vim_pathogen {
	if ![ -d ~/.vim/bundle ]; then
		echo "installing pathogen for vim"
		mkdir -p ~/.vim/autoload ~/.vim/bundle && \
		curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
	else
		echo "pathogen installed already"
	fi
}

install_homebrew
install_xcode_cli
install_vim_plugin
install_vim_with_lua
install_vim_go_ide
